name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node.js and npm
        run: sudo apt-get install nodejs npm
        
      - name: Run Test
        run: npm run test
